### ISSUE TITLE
External link referencing ukcp18-uk-marine-coastline-lowres files is outdated

### ISSUE THREAD

**Issue by harrietrs** [ukcp-data/ukcp-spatial-files#4]
The page https://ukclimateprojections-ui.metoffice.gov.uk/help/spatial_files references the wrong link for most Coastline, low resolution files.

These urls seem to have geojson in the file name, which no longer is the case, creating a 404 error.

Apologies as this github page itself is not incorrect but hopefully you can make the change happen on the website as well?

**Comment by antony-wilson** [comment]
The broken links have been fixed in the template and the production system updated. The links on https://ukclimateprojections-ui.metoffice.gov.uk/help/spatial_files to the coastline files should now work.
